djangoApp/djangoApp/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
]

djangoProject/urls.py
from django.conf.urls import include, patterns, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^$', 'tangoAds.views.home_page', name='home'),
    url(r'^pages/', include('tangoAds.urls'))
    #url(r'^admin/', include(admin.site.urls)),
)

tangoAds/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^(\d+)/$', 'tangoAds.views.view_page', name='view_page'),
    url(r'^(\d+)/add_event$', 'tangoAds.views.add_event', name='add_event'),
    url(r'^new$', 'tangoAds.views.new_page', name='new_page'),
)

tangoAds/models.py
from django.db import models

class Page(models.Model):
    pass

class Event(models.Model):
    headline = models.TextField(default='')
    page = models.ForeignKey(Page, default=None)
    

tangoAds/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from tangoAds.models import Event, Page

def home_page(request):
    return render(request, 'home.html')
    
def view_page(request, page_id):
    page = Page.objects.get(id=page_id)
    return render(request, 'page.html', {'page': page})

def new_page(request):
    page = Page.objects.create()
    Event.objects.create(headline = request.POST['event_headline'], page=page)
    return redirect('/pages/%d/' % (page.id,))

def add_event(request, page_id):
    page = Page.objects.get(id=page_id)
    Event.objects.create(headline = request.POST['event_headline'], page=page)
    return redirect('/pages/%d/' % (page.id,))

tangoAds/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Tango Ads</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet" media="screen">
	<link href="/static/base.css" rel="stylesheet" media="screen">
</head>

<body>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3 jumbotron">
			<div class="text-center">
	        	<h1>{% block header_text %}{% endblock %}</h1>
	        	<form method="POST" action="{% block form_action %}{% endblock %}">
	        		<input name="event_headline" id="id_new_event"
						class="form-control input-lg"
						placeholder="Enter a tango event"
					/>
	        		{% csrf_token %}
	        	</form>
			</div>
        </div>
    </div>
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
    		{% block table %}
    		{% endblock %}
		</div>
	</div>
</div>
</body>
</html>

tangoAds/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Add a new Tango Ads page{% endblock %}

{% block form_action %}/pages/new{% endblock %}

tangoAds/templates/page.html
{% extends 'base.html' %}

{% block header_text %}Tango Ads{% endblock %}

{% block form_action %}/pages/{{ page.id }}/add_event{% endblock %}

{% block table %}
	<table id="id_list_table" class="table">
		{% for event in page.event_set.all %}
			<tr><td>{{ forloop.counter }}. {{ event.headline }}</td></tr>
		{% endfor %}
	</table>
{% endblock %}